CREATE DATABASE IF NOT EXISTS ecommerce;

USE ecommerce;

CREATE TABLE login (
    ID_Login INTEGER PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(70) NOT NULL UNIQUE,
    Userpassword VARCHAR(70) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Names VARCHAR(60),
    Lastnames VARCHAR(60),
    Birthdate DATE NOT NULL,
    Gender ENUM('M','F','ND'),
    Phonenumber VARCHAR(50),
    Rol ENUM('ADMIN', 'USER') NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE users (
    ID_Users INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    login_id INTEGER,
    Adress VARCHAR(60),
    Active TINYINT(1) DEFAULT 1,
    Socialmedias ENUM('FACEBOOK','TWITTER','INSTAGRAM'),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (login_id) REFERENCES login(ID_Login)
);


CREATE TABLE products (
    ID_Products INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Productname VARCHAR(60) NOT NULL,
    Price INT NOT NULL,
    Productdesc VARCHAR(150) NOT NULL,
    Beantype ENUM('ARABICA', 'ROBUSTA', 'BLEND') NOT NULL,
    Category ENUM('ROASTED COFFEE', 'GROUND COFFEE', 'WHOLE BEAN COFFEE') NOT NULL DEFAULT 'ROASTED COFFEE',
    Roasted ENUM('LIGHT', 'MEDIUM', 'DARK') NOT NULL DEFAULT 'MEDIUM',
    Processing ENUM('SUNDRY', 'WASHED', 'HONEY') NOT NULL DEFAULT 'SUNDRY',
    Stock ENUM('IN STOCK', 'OUT OF STOCK', 'NOT AVAILABLE') NOT NULL DEFAULT 'IN STOCK',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE cart (
    ID_Cart INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    login_id INT,
    products_id INT,
    Quantity INT NOT NULL,
    Unitprice INT NOT NULL,
    Dateadded TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Cartstatus ENUM('IN PROGRESS', 'COMPLETED') NOT NULL DEFAULT 'IN PROGRESS',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE invoice (
    ID_Invoice INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    login_id INT,
    users_id INT,
    products_id INT,
    Purchasedate DATETIME NOT NULL,
    Shipping ENUM('WAITING FOR SHIPPING', 'BEING PREPARED', 'SHIPPED', 'DELIVERED') NOT NULL DEFAULT 'BEING PREPARED',
    Refund ENUM('YES', 'NO') NOT NULL DEFAULT 'NO',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE reviews (
    ID_Reviews INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    login_id INT,
    products_id INT,
    Reviewdescription VARCHAR(300),
    Stars ENUM('1', '2', '3', '4', '5') NOT NULL DEFAULT '3',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);



